site_name: taskcat
site_author: 'Tony Vattathil, Jay McConnell, Andrew Glenn'
site_description: Project documentation for taskcat python class.
site_url: https://avattathil.github.io/taskcat/
#site_favicon: 'images/favicon.png'
docs_dir: docs

repo_url: https://github.com/aws-quickstart/taskcat
theme: 
  name: material
  palette:
    primary: 'Light Green'
    accent: 'Blue Gray'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Home: README.md
  - API: apidocs/taskcat/index.html


extra:
  logo: images/logo.png
  social:
    - type: 'github'
      link: 'https://github.com/aws-quickstart/taskcat'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/tonyvattathil/'



markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
